### ISSUE TITLE
Rename Completed Comic Files

### ISSUE THREAD

**Issue by tutordelphia** [WilliamPWise/Prairie-World-Programming-Comics#1]
Rename the files in the completed comics folder for greater clarity and readability. 

See [here](https://prairieworldcomicsblog.wordpress.com/programming-series-in-order/) for the current ordering.

**Comment by WilliamPWise** [comment]
Would something like [this ](https://github.com/WilliamPWise/Praire-World-Programming-Comics/blob/master/Completed/Comparison-Operators.jpg)work to rename them? Or should I add a starting number to order them properly?

**Comment by tutordelphia** [comment]
I think the order is important, so I'd start them with a number. Maybe add a sub-folder if some are their own separate sequence.

**Comment by tutordelphia** [comment]
Not sure about it on the GitHub's website but if you have the repo cloned locally, changes like that are tracked. To learn about Git, you can go to: https://try.github.io/levels/1/challenges/1

The steps you'd need to do that for this are:

```
install git if you don't have it: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
git clone https://github.com/WilliamPWise/Prairie-World-Programming-Comics.git
Rename the files
git add .
git status (to review your changes)
git commit -m "renames the files"
git push (you may have to do a slightly different command the first time but when you type git push, it'll tell you exactly what to type. I'm forgetting...something like git push -u origin)
```

**Comment by WilliamPWise** [comment]
Thank you! I think I figured it out, and renamed them with numbers and folders from my computer.
